SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- Schema Hydra

-- Schema Hydra

CREATE SCHEMA IF NOT EXISTS Hydra DEFAULT CHARACTER SET utf8 ;
USE Hydra ;

-- Table mydb.Categories

CREATE TABLE IF NOT EXISTS Hydra.Categories (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  PRIMARY KEY (id)
)
ENGINE = InnoDB
COMMENT = 'table des categories';

-- Table mydb.Ressources

CREATE TABLE IF NOT EXISTS Hydra.Ressources (
  id INT NOT NULL AUTO_INCREMENT,
  link VARCHAR(255) NULL,
  name VARCHAR(255) NULL,
  description TEXT NULL,
  Categories_id INT(11) NULL,
  PRIMARY KEY (id),
  INDEX fk_Ressources_1_idx (Categories_id ASC),
  CONSTRAINT fk_Ressources_1
  FOREIGN KEY (Categories_id)
  REFERENCES Hydra.Categories (id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
)
ENGINE = InnoDB
COMMENT = 'table des ressources';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
